fs-writeback.c:1184:static int __init start_dirtytime_writeback(void)
binfmt_aout.c:410:static int __init init_aout_binfmt(void)
binfmt_script.c:116:static int __init init_script_binfmt(void)
pipe.c:1111:static int __init init_pipe_fs(void)
aio.c:249:static int __init aio_setup(void)
block_dev.c:551:void __init bdev_cache_init(void)
binfmt_elf_fdpic.c:92:static int __init init_elf_fdpic_binfmt(void)
filesystems.c:205:int __init  (char *buf)
filesystems.c:251:static int __init proc_filesystems_init(void)
nsfs.c:155:void __init nsfs_init(void)
compat_ioctl.c:1620:static int __init init_sys32_ioctl_cmp(const void *p, const void *q)
compat_ioctl.c:1632:static int __init init_sys32_ioctl(void)
fcntl.c:736:static int __init fcntl_init(void)
dcache.c:3375:static int __init set_dhash_entries(char *str)
dcache.c:3384:static void __init dcache_init_early(void)
dcache.c:3409:static void __init dcache_init(void)
dcache.c:3446:void __init vfs_caches_init_early(void)
dcache.c:3452:void __init vfs_caches_init(unsigned long mempages)
namespace.c:36:static int __init set_mhash_entries(char *str)
namespace.c:46:static int __init set_mphash_entries(char *str)
namespace.c:3064:static void __init init_mount_tree(void)
namespace.c:3094:void __init mnt_init(void)
mbcache.c:845:static int __init init_mbcache(void)
binfmt_misc.c:819:static int __init init_misc_binfmt(void)
eventpoll.c:2093:static int __init eventpoll_init(void)
anon_inodes.c:165:static int __init anon_inode_init(void)
char_dev.c:554:void __init chrdev_init(void)
inode.c:1786:static int __init set_ihash_entries(char *str)
inode.c:1798:void __init inode_init_early(void)
inode.c:1823:void __init inode_init(void)
file_table.c:312:void __init files_init(unsigned long mempages)
binfmt_flat.c:943:static int __init init_flat_binfmt(void)
locks.c:2675:static int __init proc_locks_init(void)
locks.c:2683:static int __init filelock_init(void)
binfmt_elf.c:2312:static int __init init_elf_binfmt(void)
direct-io.c:1327:static __init int dio_init(void)
buffer.c:3413:void __init buffer_init(void)
binfmt_em86.c:104:static int __init init_em86_binfmt(void)
